quarkus:
  http:
    port: 9000
  application:
    name: quarkus-demo
  log:
    level: DEBUG
  mongodb:
    connection-string: mongodb://localhost:27017
application:
  db:
    name: student
    collection: students
"%prod":
  quarkus:
    http:
      port: 8000
#  app:
#    db:
#      name: student
#      collection: students