quarkus:
  http:
    port: 9000
  application:
    name: quarkus-demo
  log:
    level: DEBUG
  mongodb:
    connection-string: mongodb://localhost:27017
    # Need to study about below properties
    read-concern: local
    read-preference: nearest
#    credentials:
#      username: root
#      password: root
#      auth-source: admin
#      auth-mechanism: SCRAM_SHA_1
application:
  db:
    name: student
    collection: students
"%prod":
  quarkus:
    http:
      port: 8000
#  app:
#    db:
#      name: student
#      collection: students